spring:
  application.name: Flower Server Application
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./data/flower
  liquibase:
    enabled: false
    change-log: classpath:db/changelog-master.xml
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: 'create-only'
    properties.hibernate.format_sql: true
server.port: 8000
logging.level:
  root: ERROR
  com.flower.server: DEBUG
  org.hibernate.SQL: DEBUG
  org.hibernate.type.descriptor.sql: TRACE
