name: Deploy Frontend

on:
    push:
        branches:
            - master

jobs:
    build_and_deply:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - run: yarn install --frozen-lockfile && yarn workspace app build

            - run: cp -r ./app/build ~

            - uses: actions/checkout@v2
              with:
                  ref: gh-pages

            - run: rm -rf *

            - run: cp -r ~/build/* .

            - run: cp ./index.html ./404.html

            - run: echo "# Deployment Branch" > README.md

            - run: |
                  git config --global user.name github-actions
                  git config --global user.email github-actions@github.com
                  git add .
                  git commit -m "[automated] Deplyed against ${{github.sha}}"
                  git push
